<?php

namespace common\models;

use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "{{%donhang}}".
 *
 * @property integer $id
 * @property string $hoten
 * @property string $diachi
 * @property string $email
 * @property string $dienthoai
 * @property double $tongtien
 * @property string $ngaylap
 * @property integer $soluong
 * @property string $ghichu
 * @property string $tinhtrang
 * @property string $ngaygiaohang
 *
 * @property Donhangchitiet[] $donhangchitiets
 */
class Donhang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%donhang}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hoten','email', 'diachi', 'dienthoai'], 'required','message'=>"{attribute} không được để trống !"],
            [['tongtien'], 'number'],
            [[ 'tongtien', 'ngaylap', 'soluong', 'ghichu','tinhtrang','ngaygiaohang'], 'safe'],
            [['soluong'], 'integer'],
            [['ghichu'], 'string'],
            [['email'], 'email','message'=>'Phải nhập đúng định dạng Email'],
            [['hoten', 'diachi', 'email'], 'string', 'max' => 100],
            [['dienthoai'], 'string', 'max' => 20],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'hoten' => 'Họ Tên',
            'diachi' => 'Địa Chỉ',
            'email' => 'Email',
            'dienthoai' => 'Số Điện Thoại',
            'tongtien' => 'Tổng Tiền',
            'ngaylap' => 'Ngày Lập',
            'soluong' => 'Số Lương',
            'ghichu' => 'Ghi Chú',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDonhangchitiets()
    {
        return $this->hasMany(Donhangchitiet::className(), ['donhang_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        $this->tongtien=Yii::$app->session->get('tongtien');
        $this->soluong=Yii::$app->session->get('tongsl');
        if($this->isNewRecord)
            $this->ngaylap= new Expression("NOW()");
        $this->ghichu="";
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        $gioHangs= Yii::$app->session->get('giohang');
        $soLuong = Yii::$app->session->get('soluonghang');
        foreach ($gioHangs as $index => $gioHang) {
            $donHangChiTiet = new Donhangchitiet();
            $donHangChiTiet->dongia=$gioHang->dongia;
            $donHangChiTiet->soluong = $soLuong[$gioHang->id];
            $donHangChiTiet->thanhtien = $gioHang->dongia * $soLuong[$gioHang->id];
            $donHangChiTiet->hanghoa_id=$gioHang->id;
            $donHangChiTiet->donhang_id=$this->id;
            $donHangChiTiet->save();

        }
        Yii::$app->session->set('giohang',null);
        Yii::$app->session->set('soluonghang',null);
        Yii::$app->session->set('tongsl',null);
        Yii::$app->session->set('tongtien',null);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
    public function beforeDelete()
    {
        Donhangchitiet::deleteAll(['donhang_id'=>$this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
