<?php

namespace common\models;

use Yii;
use common\models\base;
/**
 * This is the model class for table "nhacungcap".
 *
 * @property integer $id
 * @property string $tennhacungcap
 * @property string $code
 *
 * @property Hanghoa[] $hanghoas
 * @property
 */
class Nhacungcap extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'nhacungcap';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tennhacungcap'], 'required'],
            [['tennhacungcap', 'code'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tennhacungcap' => 'Tennhacungcap',
            'code' => 'Code',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHanghoas()
    {
        return $this->hasMany(Hanghoa::className(), ['nhacungcap_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        $this->code= base::convertStr($this->tennhacungcap);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
