<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%option_value}}".
 *
 * @property integer $id
 * @property string $image
 * @property string $name
 * @property string $description
 * @property integer $option_key_id
 *
 * @property OptionKey $optionKey
 */
class OptionValue extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%option_value}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'option_key_id'], 'required'],
            [['option_key_id'], 'integer'],
            [['image', 'description'], 'string', 'max' => 255],
            [['name'], 'string', 'max' => 128],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['option_key_id'], 'exist', 'skipOnError' => true, 'targetClass' => OptionKey::className(), 'targetAttribute' => ['option_key_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'image' => 'Image',
            'name' => 'Name',
            'description' => 'Description',
            'option_key_id' => 'Option Key ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOptionKey()
    {
        return $this->hasOne(OptionKey::className(), ['id' => 'option_key_id']);
    }
    public function beforeSave($insert)
    {
        $img = UploadedFile::getInstance($this,'image');
        if($insert){
            if(!empty($img)){
                $this->image=time().$img->name;
                $img->saveAs(dirname(dirname(__DIR__)).'/images/'.$this->image);
            }
        } else {
            if(!empty($img)){
                $this->image=time().$img->name;
                $img->saveAs(dirname(dirname(__DIR__)).'/images/'.$this->image);
                if($this->getOldAttribute('image')!=''){
                    if(file_exists(dirname(dirname(__DIR__)).'/images/'.$this->getOldAttribute('image'))){
                        unlink(dirname(dirname(__DIR__)).'/images/'.$this->getOldAttribute('image'));
                    }
                }
            } else {
                $this->image=$this->getOldAttribute('image');
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
