<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%product_option_key}}".
 *
 * @property integer $id
 * @property integer $option_key_id
 * @property integer $hanghoa_id
 *
 * @property Hanghoa $hanghoa
 * @property OptionKey $optionKey
 */
class ProductOptionKey extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%product_option_key}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['option_key_id', 'hanghoa_id'], 'required'],
            [['option_key_id', 'hanghoa_id'], 'integer'],
            [['hanghoa_id'], 'exist', 'skipOnError' => true, 'targetClass' => Hanghoa::className(), 'targetAttribute' => ['hanghoa_id' => 'id']],
            [['option_key_id'], 'exist', 'skipOnError' => true, 'targetClass' => OptionKey::className(), 'targetAttribute' => ['option_key_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'option_key_id' => 'Option Key ID',
            'hanghoa_id' => 'Hanghoa ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHanghoa()
    {
        return $this->hasOne(Hanghoa::className(), ['id' => 'hanghoa_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOptionKey()
    {
        return $this->hasOne(OptionKey::className(), ['id' => 'option_key_id']);
    }
    
    public function afterSave($insert, $changedAttributes)
    {
        
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
    public function beforeDelete()
    {
        ProductOptionValue::deleteAll(['hanghoa_id'=>$this->hanghoa_id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
