<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;
use yii\db\Expression;
use common\models\base;
/**
 * This is the model class for table "thuonghieu".
 *
 * @property integer $id
 * @property string $tenthuonghieu
 * @property string $code
 * @property string $logo
 * @property string $oldImg
 */
class Thuonghieu extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $oldImg='';
    public static function tableName()
    {
        return 'thuonghieu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tenthuonghieu'], 'required'],
            [['code','logo'], 'safe'],
            [['tenthuonghieu', 'code'], 'string', 'max' => 100],
            [['logo'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'tenthuonghieu' => 'Tenthuonghieu',
            'code' => 'Code',
            'logo' => 'Logo',
        ];
    }
    public function beforeSave($insert)
    {
        $file=UploadedFile::getInstance($this,'logo');
        $this->code = base::convertStr($this->tenthuonghieu);
        if(!empty($file)){
            if($this->oldImg!=''){
                $pathOld = dirname(dirname(__DIR__)).'/images/'.$this->oldImg;
                if(file_exists($pathOld)){
                    unlink($pathOld);
                }
            }
            $this->logo=time().$file->name;
            $path= dirname(dirname(__DIR__)).'/images/'.$this->logo;
            $file->saveAs($path);
        }
        else {
            $this->logo = $this->oldImg;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
   


}
